// ============================================================================
// FABRIC MOCK DATA — mirrors IFabricProduct shape
// Swap for real FabricProduct.find({ active: true, stitchingAvailable: true }).lean()
// ============================================================================

import type { IFabricProduct } from '@/types/product';

export const MOCK_FABRICS: IFabricProduct[] = [
    {
        _id: 'fab001',
        name: 'Egyptian Linen — Natural',
        description: 'Premium Egyptian linen, breathable and perfect for thobes and kurtas.',
        category: 'mens',
        subcategory: 'linen',
        type: 'fabric',
        price: 340,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/beach-boat'],
        featured: true,
        active: true,
        tags: ['linen', 'natural', 'breathable'],
        stockInMeters: 48,
        pricePerMeter: 340,
        fabricType: 'Linen',
        width: 58,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/beach-boat',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab002',
        name: 'Pure Cotton — Slate Blue',
        description: 'Soft weave cotton, ideal for casual kurtas and shirts.',
        category: 'mens',
        subcategory: 'cotton',
        type: 'fabric',
        price: 220,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/nature-mountains'],
        featured: false,
        active: true,
        tags: ['cotton', 'slate blue', 'casual'],
        stockInMeters: 60,
        pricePerMeter: 220,
        fabricType: 'Cotton',
        width: 54,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/nature-mountains',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab003',
        name: 'Italian Wool Blend — Charcoal',
        description: 'Luxurious mid-weight wool blend, structured and elegant.',
        category: 'mens',
        subcategory: 'wool',
        type: 'fabric',
        price: 580,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/road-safari'],
        featured: true,
        active: true,
        tags: ['wool', 'charcoal', 'luxury'],
        stockInMeters: 22,
        pricePerMeter: 580,
        fabricType: 'Wool',
        width: 60,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/road-safari',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab004',
        name: 'Silk Dupion — Champagne',
        description: 'Lustrous silk dupion with a subtle sheen, perfect for festive wear.',
        category: 'mens',
        subcategory: 'silk',
        type: 'fabric',
        price: 760,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/girl-urban-view'],
        featured: false,
        active: true,
        tags: ['silk', 'champagne', 'festive'],
        stockInMeters: 14,
        pricePerMeter: 760,
        fabricType: 'Silk',
        width: 44,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/girl-urban-view',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab005',
        name: 'Khadi Cotton — Off White',
        description: 'Hand-spun khadi, textured and authentic.',
        category: 'mens',
        subcategory: 'khadi',
        type: 'fabric',
        price: 290,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/ecommerce/accessories-bag'],
        featured: false,
        active: true,
        tags: ['khadi', 'off-white', 'handmade'],
        stockInMeters: 36,
        pricePerMeter: 290,
        fabricType: 'Khadi',
        width: 48,
        texture: undefined,
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab006',
        name: 'Premium Poplin — White',
        description: 'Crisp poplin weave, wrinkle-resistant. Great for formal thobes.',
        category: 'mens',
        subcategory: 'poplin',
        type: 'fabric',
        price: 380,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/ecommerce/shoes'],
        featured: false,
        active: true,
        tags: ['poplin', 'white', 'formal'],
        stockInMeters: 55,
        pricePerMeter: 380,
        fabricType: 'Poplin',
        width: 60,
        texture: undefined,
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

// Mock measurement profiles for a user
import type { IMeasurementProfile } from '@/types/cart';

export const MOCK_PROFILES: IMeasurementProfile[] = [
    {
        _id: 'mp001',
        profileName: 'My Default',
        garmentTypes: ['kurta'],
        isDefault: true,
        measurements: {
            neck: 15,
            chest: 40,
            waist: 34,
            shoulder: 17,
            sleeveLength: 24,
            shirtLength: 42,
        },
    },
    {
        _id: 'mp002',
        profileName: 'For Formal',
        garmentTypes: ['thobe'],
        isDefault: false,
        measurements: {
            neck: 15.5,
            chest: 42,
            shoulder: 17.5,
            sleeveLength: 25,
            shirtLength: 55,
        },
    },
    {
        _id: 'mp003',
        profileName: 'For Father',
        garmentTypes: ['other'],
        isDefault: false,
        measurements: {
            neck: 17,
            chest: 46,
            waist: 40,
            shoulder: 19,
            sleeveLength: 24,
            shirtLength: 44,
            pantLength: 40,
            pantWaist: 38,
        },
    },
];
