// ============================================================================
// FABRIC MOCK DATA — mirrors IFabricProduct shape
// Swap for real FabricProduct.find({ active: true, stitchingAvailable: true }).lean()
// ============================================================================

import type { IFabricProduct } from '@/types/product';

export const MOCK_FABRICS: IFabricProduct[] = [
    {
        _id: 'fab001',
        name: 'Egyptian Linen — Natural',
        slug: 'egyptian-linen-natural',
        description: 'Premium Egyptian linen, breathable and perfect for thobes and kurtas.',
        category: 'mens',
        subcategory: 'linen',
        type: 'fabric',
        price: 340,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/beach-boat'],
        featured: true,
        active: true,
        tags: ['linen', 'natural', 'breathable'],
        stockInMeters: 48,
        pricePerMeter: 340,
        fabricType: 'Linen',
        width: 58,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/beach-boat',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab002',
        name: 'Pure Cotton — Slate Blue',
        slug: 'pure-cotton-slate-blue',
        description: 'Soft weave cotton, ideal for casual kurtas and shirts.',
        category: 'mens',
        subcategory: 'cotton',
        type: 'fabric',
        price: 220,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/nature-mountains'],
        featured: false,
        active: true,
        tags: ['cotton', 'slate blue', 'casual'],
        stockInMeters: 60,
        pricePerMeter: 220,
        fabricType: 'Cotton',
        width: 54,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/nature-mountains',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab003',
        name: 'Italian Wool Blend — Charcoal',
        slug: 'italian-wool-blend-charcoal',
        description: 'Luxurious mid-weight wool blend, structured and elegant.',
        category: 'mens',
        subcategory: 'wool',
        type: 'fabric',
        price: 580,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/road-safari'],
        featured: true,
        active: true,
        tags: ['wool', 'charcoal', 'luxury'],
        stockInMeters: 22,
        pricePerMeter: 580,
        fabricType: 'Wool',
        width: 60,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/road-safari',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab004',
        name: 'Silk Dupion — Champagne',
        slug: 'silk-dupion-champagne',
        description: 'Lustrous silk dupion with a subtle sheen, perfect for festive wear.',
        category: 'mens',
        subcategory: 'silk',
        type: 'fabric',
        price: 760,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/girl-urban-view'],
        featured: false,
        active: true,
        tags: ['silk', 'champagne', 'festive'],
        stockInMeters: 14,
        pricePerMeter: 760,
        fabricType: 'Silk',
        width: 44,
        texture: 'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/girl-urban-view',
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab005',
        name: 'Khadi Cotton — Off White',
        slug: 'khadi-cotton-off-white',
        description: 'Hand-spun khadi, textured and authentic.',
        category: 'mens',
        subcategory: 'khadi',
        type: 'fabric',
        price: 290,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/ecommerce/accessories-bag'],
        featured: false,
        active: true,
        tags: ['khadi', 'off-white', 'handmade'],
        stockInMeters: 36,
        pricePerMeter: 290,
        fabricType: 'Khadi',
        width: 48,
        texture: undefined,
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: 'fab006',
        name: 'Premium Poplin — White',
        slug: 'premium-poplin-white',
        description: 'Crisp poplin weave, wrinkle-resistant. Great for formal thobes.',
        category: 'mens',
        subcategory: 'poplin',
        type: 'fabric',
        price: 380,
        images: ['https://res.cloudinary.com/demo/image/upload/v1/samples/ecommerce/shoes'],
        featured: false,
        active: true,
        tags: ['poplin', 'white', 'formal'],
        stockInMeters: 55,
        pricePerMeter: 380,
        fabricType: 'Poplin',
        width: 60,
        texture: undefined,
        stitchingAvailable: true,
        stitchingPrice: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

// Mock measurement profiles for a user
import type { IMeasurementProfile } from '@/types/cart';

export const MOCK_PROFILES: IMeasurementProfile[] = [
    {
        _id: 'mp001',
        profileName: 'My Default',
        garmentTypes: ['saudi_kandora'],
        isDefault: true,
        measurements: {
            length: 140,
            shoulder: 46,
            sleeveLength: 62,
            loose1: 36,
            loose2: 28,
            chest: 104,
            waist: 96,
            bottom: 72,
            neck: 40,
        },
        preferences: {
            neckType: 'cut_neck',
            fitPreference: 'medium',
            cuffType: 'simple',
        },
    },
    {
        _id: 'mp002',
        profileName: 'For Formal',
        garmentTypes: ['emirati_kandora'],
        isDefault: false,
        measurements: {
            length: 143,
            shoulder: 48,
            sleeveLength: 64,
            loose1: 38,
            loose2: 29,
            chest: 108,
            waist: 100,
            bottom: 75,
            neck: 42,
        },
        preferences: {
            neckType: 'qathari',
            fitPreference: 'slim',
            cuffType: 'french',
        },
    },
    {
        _id: 'mp003',
        profileName: 'For Father',
        garmentTypes: ['jubba'],
        isDefault: false,
        measurements: {
            length: 148,
            shoulder: 50,
            sleeveLength: 63,
            loose1: 42,
            loose2: 32,
            chest: 116,
            waist: 110,
            bottom: 80,
            neck: 44,
        },
        preferences: {
            neckType: 'full_neck',
            fitPreference: 'loose',
            cuffType: 'button',
        },
    },
];
