'use client';

import { useState } from 'react';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import MeasurementForm from '@/components/forms/MeasurementForm';
import { MeasurementFormData } from '@/lib/validations/measurement';
import { Scissors, Ruler } from 'lucide-react';
import { useCartStore, FabricCartItem } from '@/store/useCartStore';

interface StitchingModalProps {
    isOpen: boolean;
    onClose: () => void;
    product: {
        _id: string;
        name: string;
        fabricType?: string;
        pricePerMeter?: number;
        stitchingPrice?: number;
        images: string[];
    };
}

export default function StitchingModal({
    isOpen,
    onClose,
    product,
}: StitchingModalProps) {
    const [isLoading, setIsLoading] = useState(false);
    const addItem = useCartStore((state) => state.addItem);

    const handleSubmit = async (data: MeasurementFormData) => {
        setIsLoading(true);

        // Create fabric cart item with stitching details
        const fabricItem: FabricCartItem = {
            id: '', // Will be generated by the store
            productId: product._id,
            name: product.name,
            image: product.images[0] || '',
            type: 'fabric',
            pricePerMeter: product.pricePerMeter || 0,
            meters: 3, // Default 3 meters (can be made configurable later)
            quantity: 1,
            fabricType: product.fabricType,
            stitchingPrice: product.stitchingPrice,
            stitchingDetails: {
                style: data.style,
                measurements: {
                    neck: data.neck,
                    chest: data.chest,
                    waist: data.waist,
                    shoulder: data.shoulder,
                    sleeveLength: data.sleeveLength,
                    shirtLength: data.shirtLength,
                },
                notes: data.notes,
            },
        };

        // Add to cart
        addItem(fabricItem);

        console.log('✅ Added to cart:', fabricItem);

        setIsLoading(false);
        onClose();
    };

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <div className="flex items-start gap-4">
                        <div className="flex-shrink-0 w-12 h-12 rounded-full bg-emerald-100 flex items-center justify-center">
                            <Scissors className="h-6 w-6 text-emerald-600" />
                        </div>
                        <div className="flex-1">
                            <DialogTitle className="text-2xl font-serif text-navy-900">
                                Custom Stitching Service
                            </DialogTitle>
                            <DialogDescription className="mt-2">
                                Provide your measurements for a perfectly tailored garment
                            </DialogDescription>
                        </div>
                    </div>
                </DialogHeader>

                {/* Product Info */}
                <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4 space-y-3">
                    <div className="flex items-center justify-between">
                        <div>
                            <h3 className="font-semibold text-navy-900">{product.name}</h3>
                            {product.fabricType && (
                                <p className="text-sm text-gray-600">{product.fabricType}</p>
                            )}
                        </div>
                        <Badge className="bg-gold-600 text-white">
                            Stitching: ${product.stitchingPrice}
                        </Badge>
                    </div>

                    <div className="flex items-center gap-2 text-sm text-emerald-700">
                        <Ruler className="h-4 w-4" />
                        <span>All measurements should be in inches</span>
                    </div>
                </div>

                {/* Measurement Guide */}
                <div className="bg-navy-50 border border-navy-200 rounded-lg p-4">
                    <h4 className="font-semibold text-navy-900 mb-2 flex items-center gap-2">
                        <Ruler className="h-4 w-4" />
                        Measurement Tips
                    </h4>
                    <ul className="text-sm text-navy-700 space-y-1">
                        <li>• Use a flexible measuring tape</li>
                        <li>• Measure over light clothing for accuracy</li>
                        <li>• Stand straight with arms relaxed at your sides</li>
                        <li>• Have someone help you for better results</li>
                    </ul>
                </div>

                {/* Measurement Form */}
                <div className="pt-2">
                    <MeasurementForm onSubmit={handleSubmit} isLoading={isLoading} />
                </div>
            </DialogContent>
        </Dialog>
    );
}
